### ISSUE TITLE
Doesn't work with minishift 1.5.0

### ISSUE THREAD

**Issue by ffirg** [redhatdemocentral/rhcs-cloudforms-demo#2]
Thought I'd give this a test with minishift latest. 

when it comes to doing the oc new-app within init.sh you get:
error: object does not implement the Object interfaces

Full stack trace:

$ sh -ax init.sh 192.168.99.100
+ AUTHORS='Michael Surbey, Eric D. Schabell'
+ DOCKER_MAJOR_VER=17
+ DOCKER_MINOR_VER=06
+ OC_MAJOR_VER=v3
+ OC_MINOR_VER=5
+ GIT_REPO=https://github.com/redhatdemocentral/rhcs-cloudforms-demo
+ OPENSHIFT_USER=developer
+ OPENSHIFT_PWD=developer
+ HOST_IP=192.168.99.100
+ OCP_PRJ=cloudforms
+ CF_IMAGE_TEMPLATE=https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_examples/files/examples/v3.6/cfme-templates/cfme-template.yaml
+ clear
+ echo

+ echo '#####################################################################'
#####################################################################
+ echo '##                                                                 ##'
##                                                                 ##
+ echo '##  Setting up your very own                                       ##'
##  Setting up your very own                                       ##
+ echo '##                                                                 ##'
##                                                                 ##
+ echo '##    #### #      ###  #   # ####  #####  ###  ##### #   #  ####   ##'
##    #### #      ###  #   # ####  #####  ###  ##### #   #  ####   ##
+ echo '##   #     #     #   # #   # #   # #     #   # #   # ## ## #       ##'
##   #     #     #   # #   # #   # #     #   # #   # ## ## #       ##
+ echo '##   #     #     #   # #   # #   # ####  #   # ##### # # #  ###    ##'
##   #     #     #   # #   # #   # ####  #   # ##### # # #  ###    ##
+ echo '##   #     #     #   # #   # #   # #     #   # #  #  #   #     #   ##'
##   #     #     #   # #   # #   # #     #   # #  #  #   #     #   ##
+ echo '##    #### #####  ###   ###  ####  #      ###  #   # #   # ####    ##'
##    #### #####  ###   ###  ####  #      ###  #   # #   # ####    ##
+ echo '##                                                                 ##'
##                                                                 ##
+ echo '##  https://github.com/redhatdemocentral/rhcs-cloudforms-demo      ##'
##  https://github.com/redhatdemocentral/rhcs-cloudforms-demo      ##
+ echo '##                                                                 ##'
##                                                                 ##
+ echo '##  Contributors: Michael Surbey, Eric D. Schabell                 ##'
##  Contributors: Michael Surbey, Eric D. Schabell                 ##
+ echo '##                                                                 ##'
##                                                                 ##
+ echo '#####################################################################'
#####################################################################
+ echo

+ '[' 1 -eq 1 ']'
+ valid_ip 192.168.99.100
+ local ip=192.168.99.100
+ local stat=1
+ [[ 192.168.99.100 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
+ OIFS='
'
+ IFS=.
+ ip=($ip)
+ IFS='
'
+ [[ 192 -le 255 ]]
+ [[ 168 -le 255 ]]
+ [[ 99 -le 255 ]]
+ [[ 100 -le 255 ]]
+ stat=0
+ return 0
+ echo 'OpenShift host given is a valid IP...'
OpenShift host given is a valid IP...
+ HOST_IP=192.168.99.100
+ echo

+ echo 'Proceeding with OpenShift host: 192.168.99.100...'
Proceeding with OpenShift host: 192.168.99.100...
+ echo

+ command -v oc -v
+ echo 'OpenShift commandline tooling is installed...'
OpenShift commandline tooling is installed...
+ echo

+ echo 'Logging in to OpenShift as developer...'
Logging in to OpenShift as developer...
+ echo

+ oc login 192.168.99.100:8443 --password=developer --username=developer
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * cloudforms
    default
    kube-public
    kube-system
    openshift
    openshift-infra

Using project "cloudforms".
+ '[' 0 -ne 0 ']'
+ echo

+ echo 'Creating a new project...'
Creating a new project...
+ echo

+ oc new-project cloudforms
Error from server: project.project.openshift.io "cloudforms" already exists
+ echo

+ echo 'Logging in to OpenShift as system admin...'
Logging in to OpenShift as system admin...
+ echo

+ oc login 192.168.99.100:8443 -u system:admin
Logged into "https://192.168.99.100:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * cloudforms
    default
    kube-public
    kube-system
    openshift
    openshift-infra

Using project "cloudforms".
+ '[' 0 -ne 0 ']'
+ echo

+ echo 'Adding policy for service account to run CloudForms...'
Adding policy for service account to run CloudForms...
+ echo

+ oc adm policy add-scc-to-user anyuid system:serviceaccount:cloudforms:cfme-anyuid
+ '[' 0 -ne 0 ']'
+ echo

+ echo 'Setting policy privileges for running CloudForms...'
Setting policy privileges for running CloudForms...
+ echo

+ oc adm policy add-scc-to-user privileged system:serviceaccount:cloudforms:default
+ '[' 0 -ne 0 ']'
+ echo

+ echo 'Importing CloudForms image template...'
Importing CloudForms image template...
+ echo

+ oc create -f https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_examples/files/examples/v3.6/cfme-templates/cfme-template.yaml -n openshift
Error from server: error when creating "https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_examples/files/examples/v3.6/cfme-templates/cfme-template.yaml": templates.template.openshift.io "cloudforms" already exists
+ echo

+ echo 'Logging in to OpenShift as developer...'
Logging in to OpenShift as developer...
+ echo

+ oc login 192.168.99.100:8443 --username=developer --password=developer
Login successful.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * cloudforms
    default
    kube-public
    kube-system
    openshift
    openshift-infra

Using project "cloudforms".
+ '[' 0 -ne 0 ']'
+ echo

+ echo 'Installing CloudForms...'
Installing CloudForms...
+ echo

+ oc new-app -p=APPLICATION_MEM_REQ=3072Mi --template=cloudforms
--> Deploying template "openshift/cloudforms" to project cloudforms

     cloudforms
     ---------
     CloudForms appliance with persistent storage

     * With parameters:
        * Name=cloudforms
        * PostgreSQL Service Name=postgresql
        * PostgreSQL User=root
        * PostgreSQL Password=du7XrcKp # generated
        * PostgreSQL Database Name=vmdb_production
        * Application Database Region=0
        * Memcached Service Name=memcached
        * Memcached Max Memory=64
        * Memcached Max Connections=1024
        * Memcached Slab Page Size=1m
        * PostgreSQL Max Connections=100
        * PostgreSQL Shared Buffer Amount=256MB
        * Application Min CPU Requested=1000m
        * PostgreSQL Min CPU Requested=500m
        * Memcached Min CPU Requested=200m
        * Application Min RAM Requested=3072Mi
        * PostgreSQL Min RAM Requested=1024Mi
        * Memcached Min RAM Requested=64Mi
        * Application Max RAM Limit=16384Mi
        * PostgreSQL Max RAM Limit=8192Mi
        * Memcached Max RAM Limit=256Mi
        * PostgreSQL Image Name=registry.access.redhat.com/cloudforms45/cfme-openshift-postgresql
        * PostgreSQL Image Tag=latest
        * Memcached Image Name=registry.access.redhat.com/cloudforms45/cfme-openshift-memcached
        * Memcached Image Tag=latest
        * Application Image Name=registry.access.redhat.com/cloudforms45/cfme-openshift-app
        * Application Image Tag=latest
        * Application Hostname=
        * Application Init Delay=15
        * Application Volume Capacity=5Gi
        * Application Region Volume Capacity=5Gi
        * Database Volume Capacity=15Gi

error: object does not implement the Object interfaces
+ '[' 1 -ne 0 ']'
+ echo

+ echo 'Error occurred during install of CloudForms!'
Error occurred during install of CloudForms!
+ exit

**Comment by eschabell** [comment]
This is for an OpenShift Container Platform 3.6.... is that what mini-shift gives you or does it pull an OpenShift Origin version?

What version of oc client do you use here... it needs to be v3.6.173.0.21.

**Comment by eschabell** [comment]
No plans to support minishift using OpenShift Origin (community).
